rootProject.name = "Concurrency"
include("UnisexBathroom")
include("UnisexBathroom")
include("UnisexBathroom")
include("UnisexBathroom")
include("FaneuilHall")
include("SenateBus")
include("RoomParty")
include("ClassicProblems")
include("DiningSavages")
include("BarberShop")
include("ComplexBarberShop")